name: native_device_info
description: "A Flutter plugin to monitor battery level and charging status."
version: 0.0.1

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.native.device.info.native_device_info
        pluginClass: NativeDeviceInfoPlugin
      ios:
        pluginClass: NativeDeviceInfoPlugin
